### ISSUE TITLE
Missing DLL free version

### ISSUE THREAD

**Issue by Xela124** [RenderHeads/UnityPlugin-AVProLiveCamera#22]
**Describe the bug**
Hello,
I want to try your plugin before buy it. I downloaded the free trial version on your website and import it into Unity.
But Unity says me that He missing DLL File. 

Where can I find this DLL since I only have the package you give ? 

Thank you

**Your Setup (please complete the following information):**
 - Unity version: Tested with 2019.x & 2020.x
 - AVPro Live Camera version: Latest on your web site
 - Operating system version: Windows 10 - 64 bits
 - Hardware/webcam model: Logiech HD Pro C 920

**Screenshots**
![image](https://user-images.githubusercontent.com/51998689/99234235-8f9f0900-27f4-11eb-846f-9ce6d2ce08d8.png)

**Comment by Xela124** [comment]
Sorry for the quick up but I notice something : 

Here are the file (free version) when I emport to Unity : 
![image](https://user-images.githubusercontent.com/51998689/99234639-1522b900-27f5-11eb-918c-be5e7e4e7145.png)

Here are the file (On asset store "Package content") : 
There are the Dlll files that are missing in the free version
![image](https://user-images.githubusercontent.com/51998689/99234759-3c798600-27f5-11eb-9cd6-72950916af6d.png)

**Comment by AndrewRH** [comment]
Hi,
I just downloaded the trial version and it seems fine to me:
![image](https://user-images.githubusercontent.com/5418126/99292681-78ced580-2839-11eb-8b4e-016c5cbaa521.png)
Where are you downloading it from?  The link should be:
http://downloads.renderheads.com/2020/UnityPlugin-AVProLiveCamera-Latest-Trial.unitypackage

Thanks,

**Comment by Xela124** [comment]
Hi Andrew,
Thank for your answer. 
I downloaded it from your site. I try your link and now I can import the plugin folder :) 
Thnak for your help

**Comment by AndrewRH** [comment]
Great, I'm glad that's solved.  I'll close this issue now.
