### ISSUE TITLE
OBS Virtual Camera Crashes

### ISSUE THREAD

**Issue by farazkhalidsiddiqui** [RenderHeads/UnityPlugin-AVProLiveCamera#27]
Hi,
Unity Crashes if OBS virtual camera feed is flipped from OBS and selecting that camera in AVPro live camera.
Looking forward to its solution.
Thanks.

**Comment by AndrewRH** [comment]
Thanks for reporting this @farazkhalidsiddiqui  - well we found the problem, it's related to the pixel format.  This is all covered in issue #23  so I will close this thread here, but we should have this fixed soon.
