### ISSUE TITLE
Question about AVProLiveCamera API

### ISSUE THREAD

**Issue by fenneishi** [RenderHeads/UnityPlugin-AVProLiveCamera#36]
hi,
     What is “videoInputIndex”  and "_preferPreviewPin" use for? 
     

> `​AVProLiveCameraPlugin.StartDevice(_deviceIndex, internalModeIndex, modeFrameRateIndex, videoInputIndex, _preferPreviewPin)`

     Do you have the doc of API?
     We have so many question about the demo and the API In AVProLiveCamera.

**Comment by kahnivore** [comment]
Hi @fenneishi 

We don't actually have an API reference - the demo scenes were intended to serve that purpose. But agree it is a good idea to make one - I've logged this as an enhancement that we can attend to in the future #37.

As for your questions about videoInputIndex and _preferPreviewPin:

The videoInputIndex is for certain TV capture cards that have various inputs (such as HDMI, composite input, etc). The index is then used to select which input. In most cases, it's not something you'd need to worry about, and can leave set to the default of -1. 

_preferPreviewPin is an advanced feature, which again, you could most likely ignore and leave set to the default. It's a technicality of the DirectShow API, which basically creates two pins on the node of the created input - a preview pin, and a render pin. In some cases, with certain devices, these pins behave differently, so some users might find this option useful. 

Let us know if you have further questions.
