### ISSUE TITLE
Hotswapping only updates when device is added. Not removed.

### ISSUE THREAD

**Issue by nickhudson4** [RenderHeads/UnityPlugin-AVProLiveCamera#42]
AVProLiveCameraPlugin.GetNumDevices() does not update when device is unplugged.

Note I have both SupportHotSwapping and UpdateHotSwap on.

**Comment by nickhudson4** [comment]
The device drivers are up to date. And I am using the Logitech C505 HD Webcam as well as the OBS virtual device.

**Comment by Chris-RH** [comment]
I'm wondering if the OBS virtual device is confusing it perhaps. Have you tried disabling/uninstalling it?

**Comment by nickhudson4** [comment]
To clarify, hotswapping it does appear to be working in the sense that I can disconnect and re-connect a device and have it start again. The issue I am having is that the devices list and NumDevices of AVProLiveCameraManager is not updating when a device is disconnected. Is it suppose to do this? Because in the manager, the update function doesn't appear to remove devices, only add. 
`	if (_supportHotSwapping && _hotSwapCounter.isOver())
			{
				if (AVProLiveCameraPlugin.UpdateDevicesConnected())
				{
					// Add any new devices
					AddNewDevices();
				}
			}
			_hotSwapCounter.incriment();`

**Comment by Chris-RH** [comment]
oh right, yes, that is how it is supposed to work; its not supposed to remove them :)
