### ISSUE TITLE
The picture of the camera is blank

### ISSUE THREAD

**Issue by Senfee-Cheng** [RenderHeads/UnityPlugin-AVProLiveCamera#43]
**Describe the bug**
The picture of the camera is blank

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Live Camera version: 
 - Operating system version: 
 - Hardware/webcam model: 
 - Video mode (resolution, frame-rate, etc): 

**To Reproduce**

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![图片](https://user-images.githubusercontent.com/20067002/179655977-adb17714-1e56-4c89-ae07-1f06d6260fa7.png)

**Videos**
If applicable, add a copy of your video or the URL

**Comment by Chris-RH** [comment]
Hi @Senfee-Cheng 
You've not really given enough details.

- I use the same webcam as you are using.  
- I open up a new project (I'm using Unity 2021.3.4 and DX11) and import AVPro LiveCam (version 2.9.1)
- I open up the demoscene (CameraExplorerDemo or DefaultCameraDemo are fine)
- Play Scene and select camera from dropdown menu)
- It shows the picture from my webcam

1. Does it work in the demo scenes?
2. Are your webcam drivers up  to date?
3. Does the webcam work in other software?

**Comment by Chris-RH** [comment]
Closed due to lack of response, please reopen and provide more details if this is still an issue.
