### ISSUE TITLE
 can't get the closest mode when the aspect is the same

### ISSUE THREAD

**Issue by GodZza** [RenderHeads/UnityPlugin-AVProLiveCamera#48]
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**
call the AVProLiveCameraDevice.GetClosestMode function, cannot get the closest mode.

**Your Setup (please complete the following information):**
 - Unity version: 2023.3.5f1
 - AVPro Live Camera version:  2.9.3
 - Operating system version: windows 11
 - Hardware/webcam model: HD Camera
 - Video mode (resolution, frame-rate, etc):  352x288

**To Reproduce**
1. Go to 'AVProLiveCameraDevice.GetClosestMode' script . at line:734 (after =>// If we haven't found an exact match, find by closest area)
2. the code is 'float aspect = (float)width * (float)height;' in the project.  but 'float aspect=(float)width / (float)height;' is correct.

**Logs**

**Screenshots**

**Videos**

Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
We are looking into fixing this, thanks
