### ISSUE TITLE
AVProLiveCamera is not support DirectX 12

### ISSUE THREAD

**Issue by Isetta-Han** [RenderHeads/UnityPlugin-AVProLiveCamera#52]
https://forum.unity.com/threads/dx12-is-out-of-experimental-since-2022-2-0a17.1301571/
DX12 is out of experimental since 2022.2.0a17, but AVProLiveCamera is not support DirectX 12, request for  suport DX12

**Comment by Chris-RH** [comment]
Hi, this is already listed under enhancement requests - https://github.com/RenderHeads/UnityPlugin-AVProLiveCamera/issues/31
