### ISSUE TITLE
Camera feed freezes sometimes

### ISSUE THREAD

**Issue by gekkyo** [RenderHeads/UnityPlugin-AVProLiveCamera#55]
### AVPro Live Camera edition

Full

### AVPro Live Camera Version

2.9.3

### Your question

Hi. I have purchased the plugin and am using it for a commercial signage project.
It is working great, but I'm encountering a issue and would appreciate some help.

Every 2 to 3 days, the camera feed freezes, and I've been receiving inquiries from my client.
This signage operates for about 8 hours a day, and restarting the machine or the application during operation is not allowed,
which is causing some difficulties.

I am working on detecting when the freeze occurs in order to automatically reset the camera feed.
In that case, what would be the best approach to detect the freeze?

In the similar [issue](https://github.com/RenderHeads/UnityPlugin-AVProLiveCamera/issues/25) Andrew suggested to monitor the texture update index. 
Specifically, how do I do that?

**Comment by Chris-RH** [comment]
We need some more information please

1. Unity version:
2. Windows version:
3. Graphics API:
4. Hardware and/or Webcam name/model number:
5. Computer hardware that app is running on, to include CPU, GPU, RAM etc):
6. Details of video mode you are using, to include: resolution, frame rate, and colour mode:
7. Does the freezing occur within the 8 hour window of operation or is it only if running for longer than 8 hours?
8. Have they tried starting restarting it every morning?

**Comment by RichRH** [comment]
Hi @gekkyo,

I believe Andrew was referring to monitoring something like 'AVProLiveCameraPlugin.GetLastFrameUploaded(deviceIndex)' or 'device.DisplayFPS' which will only be changing if new frames are being fed through.

Therefore you can run some kind of timer and if there hasn't been a change within a certain time period (depends how fine you want to be, but e.g. a second) then you can detect a freeze.

Cheers,

**Comment by gekkyo** [comment]
Thank you for your reply.

@Chris-RH 
Here is my detailed environment.

1. 2022.3.21f1
2. WIndows 11 Pro 23H2
3. not sure. The graphics api is set to AUTO in the unity's build setting.
4. MAGEWELL USB CAPTURE HDMI GEN 2
5. Intel Core i7-14700k / GeForce RTX 4070 / RAM 64GB / SSD 4TB NVMe Gen4
6. 1920 x 1080 / 30fps / RGB24
7. It happens within the 8 hour window. It happens randomly. Sometimes it occurs after 10 minutes, and other times after several hours.
8. They shutdown the PC every day after business hours, then start it every morning.

@RichRH 
Thank you for your help. I'll try monitoring those values and see if I could restart the camera feed when it happens.
By the way, in order to restart the video feed, the code below is correct?

AVProLiveCameraComponent.Device.Stop();
AVProLiveCameraComponent.Begin();

**Comment by RichRH** [comment]
Hi @gekkyo,

Sorry, missed your message - depends on your usage but the following can be used to fully restart a feed if the above doesn't work (see our 'AVProLiveCameraCameraExplorerDemo.cs' as an example - you might need to pass in modes etc.. depending on what you're doing):

AVProLiveCameraDevice device = AVProLiveCameraManager.Instance.GetDevice( X );
device.Close();
device.Start();

Cheers,

**Comment by gekkyo** [comment]
@RichRH 
I have confirmed that monitoring "AVProLiveCameraPlugin.GetLastFrameUploaded(deviceIndex)" allows me to detect a freeze. So, I will incorporating the feed reset process when that happens.
Thanks for your support!
