### ISSUE TITLE
Randomly resolution and fps init

### ISSUE THREAD

**Issue by Filaind** [RenderHeads/UnityPlugin-AVProLiveCamera#7]
We have a problem with a camera init.
So, we set a camera index and mode, invoke _liveCamera.Begin();

But, camera starting on randomly resolution and fps.

Example:
Mode 0 = 1920x1080 30fps

But camera start in 640x480 24fps.
If we invoke repeately _liveCamera.Begin(); camera can start normaly in 1920x1080 30fps.

This bug contains on different camera inputs

AVPro Live Camera - Version 2.8.0

**Comment by AndrewRH** [comment]
Could you show us the code you're using to set the index and device, and how you're calling Begin()?

Thanks,

**Comment by Filaind** [comment]
@AndrewRH 
```
    public void SetDevice(int id)
    {
        cameraInputSettings.cameraIndex = id;
        _liveCamera._deviceSelection = AVProLiveCamera.SelectDeviceBy.Index;
        _liveCamera._desiredDeviceIndex = id;
        _liveCamera.Begin();
        MakeDropdowns();
    }

    public void SetResolution(int id)
    {
        cameraInputSettings.modeIndex = id;
        _liveCamera._modeSelection = AVProLiveCamera.SelectModeBy.Index;
        _liveCamera._desiredModeIndex = id;
        _liveCamera.Begin();
    }
```

**Comment by AndrewRH** [comment]
Thanks....I can't see anything wrong with that code!  We're investigating...

**Comment by AndrewRH** [comment]
@Filaind  Which webcam device is this happening with?

**Comment by Chris-RH** [comment]
Could not reproduce
